/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uk.gov.ons.fsdr.adeccomock;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class AdeccoMock {

    public static void main(String[] args) {
        SpringApplication.run(AdeccoMock.class, args);
    }
}

